/**
 * Decoder Report generated by AI
 * This is the final output shown to users
 */
export type DecoderReport = {
  summary: string; // 2-3 sentence reality summary
  red_flags: Array<{
    title: string;
    description: string;
    source_field?: string; // Which field triggered this flag
  }>;
  positives: Array<{
    title: string;
    description: string;
  }>;
  scorecard: {
    value: { score: number; rationale: string }; // 0-10
    livability: { score: number; rationale: string }; // 0-10
    noise_light: { score: number; rationale: string }; // 0-10
    hazards: { score: number; rationale: string }; // 0-10
    transparency: { score: number; rationale: string }; // 0-10
    total: number; // 0-100
  };
  follow_up_questions: string[]; // Up to 6 questions
  caption: string; // 120-char one-liner
  generated_at: string;
  version?: string; // Schema version for cache busting
};

